#ifndef _BOARDS_THINGOE_1E_H
#define _BOARDS_THINGOE_1E_H

#define PICO_DEFAULT_UART 0
#define PICO_DEFAULT_UART_TX_PIN 12
#define PICO_DEFAULT_UART_RX_PIN 13

#define PICO_DEFAULT_LED_PIN 17

#define PICO_DEFAULT_I2C 1
#define PICO_DEFAULT_I2C_SDA_PIN 18
#define PICO_DEFAULT_I2C_SCL_PIN 19

#define PICO_DEFAULT_EE_WP_PIN 20

#define PICO_BOOT_STAGE2_CHOOSE_GENERIC_03H 1
#define PICO_FLASH_SIZE_BYTES (512 * 1024)

// All boards have B1 RP2040
#ifndef PICO_RP2040_B0_SUPPORTED
#define PICO_RP2040_B0_SUPPORTED 0
#endif

#include "boards/pico.h"

#undef PICO_BOOT_STAGE2_CHOOSE_W25Q080

#endif